title: Memgrafter's Record
description: Certain Notations concerning the Cross Road of Artifice and the Mind.
theme: just-the-docs

url: https://memgrafter.github.io/record/

aux_links:
  "gh": https://github.com/robbintt
