title: Memgrafter's Record
description: <strong>Certain Notations</strong> concerning the Cross Road of <strong>Artifice</strong> and the <strong>Mind</strong>.
theme: moonwalk

url: https://memgrafter.github.io/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
