title: My Awesome Blog
description: A place for my thoughts and writings.
theme: minima

url: https://memgrafter.github.io/record/ # Keep your existing URL structure

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
